# Pydantic schemas (request/response). Per-domain schemas live in separate modules.
from app.schemas.admin import AdminEventItem, AdminStats, AdminUserItem, ApproveBody, PlatformSettingItem, PlatformSettingUpdate
from app.schemas.dashboard import (
    ActivityFeedItem, KpiItem, OrganizerDashboardResponse,
    OrganizerTimeSeriesResponse, StatusBreakdown, TimeSeriesPoint,
)
from app.schemas.event import (
    AddEventOrganizerBody, CancelBody, CustomerHistoryItem, EVENT_GENRES,
    EventCreate, EventDiscountCreate, EventDiscountResponse,
    EventImageResponse, EventOrganizerItem,
    EventPostCreate, EventPostResponse, EventResponse, EventUpdate,
    EventVenueInfo, ExtendFundingBody, ExtensionApprovalAction,
    MapEventMarker, OrganizerTrustInfo, SetEventDateBody, UnregisterResponse,
)
from app.schemas.funding import (
    FundingSummaryResponse, MyPledgeItem, OrganizerPledgeItem, PledgeBody,
    PledgePreviewResponse, PledgeReceiptResponse, PledgeResponse,
    UnpledgeResponse,
)
from app.schemas.registration import RegistrationDecisionBody, RegistrationResponse
from app.schemas.ticket import (
    PurchaseGroupReceiptResponse,
    ScanTicketBody,
    ScanTicketResponse,
    TicketPricePreviewResponse,
    TicketPurchaseBody,
    TicketReceiptResponse,
    TicketSaleResponse,
    TicketSalesStatsResponse,
    TicketSummaryItem,
    TicketTierCreate,
    TicketTierResponse,
    TicketTierUpdate,
    UserDiscountBody,
)
from app.schemas.ticket_strategy import (
    TicketStrategyCreate,
    TicketStrategyResponse,
    TicketStrategyTierInput,
    TicketStrategyTierResponse,
    TicketStrategyUpdate,
)
from app.schemas.discount_strategy import DiscountStrategyCreate, DiscountStrategyResponse, DiscountStrategyUpdate
from app.schemas.user import MeResponse, MeUpdate, VerifyBody, VerifyResponse
from app.schemas.venue import VenueCreate, VenueResponse, VenueUpdate

__all__ = [
    "AddEventOrganizerBody",
    "CancelBody",
    "AdminEventItem",
    "AdminStats",
    "AdminUserItem",
    "ApproveBody",
    "PlatformSettingItem",
    "PlatformSettingUpdate",
    "CustomerHistoryItem",
    "EVENT_GENRES",
    "EventCreate",
    "EventDiscountCreate",
    "EventDiscountResponse",
    "EventImageResponse",
    "EventOrganizerItem",
    "EventPostCreate",
    "EventPostResponse",
    "EventResponse",
    "EventUpdate",
    "EventVenueInfo",
    "ExtendFundingBody",
    "OrganizerTrustInfo",
    "ExtensionApprovalAction",
    "SetEventDateBody",
    "FundingSummaryResponse",
    "MyPledgeItem",
    "OrganizerPledgeItem",
    "MapEventMarker",
    "MeResponse",
    "MeUpdate",
    "PledgeBody",
    "PledgePreviewResponse",
    "PledgeReceiptResponse",
    "PledgeResponse",
    "UnpledgeResponse",
    "RegistrationDecisionBody",
    "RegistrationResponse",
    "PurchaseGroupReceiptResponse",
    "ScanTicketBody",
    "ScanTicketResponse",
    "TicketPricePreviewResponse",
    "TicketPurchaseBody",
    "TicketReceiptResponse",
    "TicketSaleResponse",
    "TicketSalesStatsResponse",
    "TicketSummaryItem",
    "TicketTierCreate",
    "TicketTierResponse",
    "TicketTierUpdate",
    "UserDiscountBody",
    "TicketStrategyCreate",
    "TicketStrategyResponse",
    "TicketStrategyTierInput",
    "TicketStrategyTierResponse",
    "TicketStrategyUpdate",
    "DiscountStrategyCreate",
    "DiscountStrategyResponse",
    "DiscountStrategyUpdate",
    "VenueCreate",
    "VenueResponse",
    "VenueUpdate",
    "UnregisterResponse",
    "VerifyBody",
    "VerifyResponse",
    "ActivityFeedItem",
    "KpiItem",
    "OrganizerDashboardResponse",
    "OrganizerTimeSeriesResponse",
    "StatusBreakdown",
    "TimeSeriesPoint",
]
